-- Create departments table for French departments
CREATE TABLE IF NOT EXISTS departments (
  id SERIAL PRIMARY KEY,
  code VARCHAR(3) UNIQUE NOT NULL,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert French departments
INSERT INTO departments (code, name, slug) VALUES
('01', 'Ain', 'ain'),
('02', 'Aisne', 'aisne'),
('03', 'Allier', 'allier'),
('04', 'Alpes-de-Haute-Provence', 'alpes-de-haute-provence'),
('05', 'Hautes-Alpes', 'hautes-alpes'),
('06', 'Alpes-Maritimes', 'alpes-maritimes'),
('07', 'Ardèche', 'ardeche'),
('08', 'Ardennes', 'ardennes'),
('09', 'Ariège', 'ariege'),
('10', 'Aube', 'aube'),
('11', 'Aude', 'aude'),
('12', 'Aveyron', 'aveyron'),
('13', 'Bouches-du-Rhône', 'bouches-du-rhone'),
('14', 'Calvados', 'calvados'),
('15', 'Cantal', 'cantal'),
('16', 'Charente', 'charente'),
('17', 'Charente-Maritime', 'charente-maritime'),
('18', 'Cher', 'cher'),
('19', 'Corrèze', 'correze'),
('21', 'Côte-d''Or', 'cote-dor'),
('22', 'Côtes-d''Armor', 'cotes-darmor'),
('23', 'Creuse', 'creuse'),
('24', 'Dordogne', 'dordogne'),
('25', 'Doubs', 'doubs'),
('26', 'Drôme', 'drome'),
('27', 'Eure', 'eure'),
('28', 'Eure-et-Loir', 'eure-et-loir'),
('29', 'Finistère', 'finistere'),
('30', 'Gard', 'gard'),
('31', 'Haute-Garonne', 'haute-garonne'),
('32', 'Gers', 'gers'),
('33', 'Gironde', 'gironde'),
('34', 'Hérault', 'herault'),
('35', 'Ille-et-Vilaine', 'ille-et-vilaine'),
('36', 'Indre', 'indre'),
('37', 'Indre-et-Loire', 'indre-et-loire'),
('38', 'Isère', 'isere'),
('39', 'Jura', 'jura'),
('40', 'Landes', 'landes'),
('41', 'Loir-et-Cher', 'loir-et-cher'),
('42', 'Loire', 'loire'),
('43', 'Haute-Loire', 'haute-loire'),
('44', 'Loire-Atlantique', 'loire-atlantique'),
('45', 'Loiret', 'loiret'),
('46', 'Lot', 'lot'),
('47', 'Lot-et-Garonne', 'lot-et-garonne'),
('48', 'Lozère', 'lozere'),
('49', 'Maine-et-Loire', 'maine-et-loire'),
('50', 'Manche', 'manche'),
('51', 'Marne', 'marne'),
('52', 'Haute-Marne', 'haute-marne'),
('53', 'Mayenne', 'mayenne'),
('54', 'Meurthe-et-Moselle', 'meurthe-et-moselle'),
('55', 'Meuse', 'meuse'),
('56', 'Morbihan', 'morbihan'),
('57', 'Moselle', 'moselle'),
('58', 'Nièvre', 'nievre'),
('59', 'Nord', 'nord'),
('60', 'Oise', 'oise'),
('61', 'Orne', 'orne'),
('62', 'Pas-de-Calais', 'pas-de-calais'),
('63', 'Puy-de-Dôme', 'puy-de-dome'),
('64', 'Pyrénées-Atlantiques', 'pyrenees-atlantiques'),
('65', 'Hautes-Pyrénées', 'hautes-pyrenees'),
('66', 'Pyrénées-Orientales', 'pyrenees-orientales'),
('67', 'Bas-Rhin', 'bas-rhin'),
('68', 'Haut-Rhin', 'haut-rhin'),
('69', 'Rhône', 'rhone'),
('70', 'Haute-Saône', 'haute-saone'),
('71', 'Saône-et-Loire', 'saone-et-loire'),
('72', 'Sarthe', 'sarthe'),
('73', 'Savoie', 'savoie'),
('74', 'Haute-Savoie', 'haute-savoie'),
('75', 'Paris', 'paris'),
('76', 'Seine-Maritime', 'seine-maritime'),
('77', 'Seine-et-Marne', 'seine-et-marne'),
('78', 'Yvelines', 'yvelines'),
('79', 'Deux-Sèvres', 'deux-sevres'),
('80', 'Somme', 'somme'),
('81', 'Tarn', 'tarn'),
('82', 'Tarn-et-Garonne', 'tarn-et-garonne'),
('83', 'Var', 'var'),
('84', 'Vaucluse', 'vaucluse'),
('85', 'Vendée', 'vendee'),
('86', 'Vienne', 'vienne'),
('87', 'Haute-Vienne', 'haute-vienne'),
('88', 'Vosges', 'vosges'),
('89', 'Yonne', 'yonne'),
('90', 'Territoire de Belfort', 'territoire-de-belfort'),
('91', 'Essonne', 'essonne'),
('92', 'Hauts-de-Seine', 'hauts-de-seine'),
('93', 'Seine-Saint-Denis', 'seine-saint-denis'),
('94', 'Val-de-Marne', 'val-de-marne'),
('95', 'Val-d''Oise', 'val-doise')
ON CONFLICT (code) DO NOTHING;
